#!/bin/bash
# Inspect the OCI spec generated by ctr --with-ns
ctr -n mill run \
    --snapshotter overlayfs \
    --with-ns "network:/var/run/netns/mill-0" \
    docker.io/library/busybox:latest \
    test-inspect-spec \
    sleep 60 &

sleep 2

echo "=== OCI spec namespaces from ctr --with-ns ==="
cat /run/containerd/io.containerd.runtime.v2.task/mill/test-inspect-spec/config.json | python3 -m json.tool | grep -A30 '"namespaces"' 2>/dev/null || echo "(config not found)"

echo "=== Rootfs contents ==="
ls /run/containerd/io.containerd.runtime.v2.task/mill/test-inspect-spec/rootfs/ 2>/dev/null || echo "(rootfs not found)"

# Kill and cleanup
ctr -n mill tasks kill test-inspect-spec --signal SIGKILL 2>/dev/null
wait
ctr -n mill tasks delete test-inspect-spec 2>/dev/null
ctr -n mill containers delete test-inspect-spec 2>/dev/null
echo "Done."
